language: python
python:
  - "pypy"
  - "2.7"
  - "3.2"
  - "3.3"
#  - "2.6"  # XXX: Importlib dep?
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# # command to run tests
script: nosetests
notifications:
  email:
    - paultag@gmail.com
  irc:
    channels:
      - "irc.freenode.org#woo-city-commits"
    on_success: always
    on_failure: always
    use_notice: true
